## Numpy

* Numerical python or numeric python
* NumPy is a programming language that deals with multi-dimensional arrays and matrices.
* NumPy supports a large number of mathematical 

## why use NumPY

* Numpy is a memory efficiency ,meaning it can handle the vast amount of data more accessible thean any other library.
* espically for matrix multiplication and reshaping


In [7]:
import numpy as np


In [21]:
import numpy as np

print(np.__version__)

1.19.2


In [23]:
print(np.array([2,3,4,5]))

[2 3 4 5]


In [22]:
a1=np.array([3,5,6,7])
a2=np.array([1,2,8,9])
print(a1+a2)
print(a1-a2)

[ 4  7 14 16]
[ 2  3 -2 -2]


In [24]:
print(a1)
print(a2)
np.hstack((a1,a2))

[3 5 6 7]
[1 2 8 9]


array([3, 5, 6, 7, 1, 2, 8, 9])

In [25]:
print(a1)
print(a2)
np.vstack((a1,a2))

[3 5 6 7]
[1 2 8 9]


array([[3, 5, 6, 7],
       [1, 2, 8, 9]])

In [26]:
a1.std()

1.479019945774904

In [27]:
a1.mean()

5.25

In [29]:
np.median(a1)

5.5

In [36]:
np.random.normal(5,4,10)

array([2.06978485, 8.46811882, 3.23891253, 1.14384264, 6.99552354,
       1.40669058, 3.8414272 , 8.4255478 , 3.41699085, 4.1684461 ])

In [39]:
d=np.random.randint(1,30,(3,3))
d

array([[ 8,  2,  8],
       [14, 29, 12],
       [ 3, 11, 23]])

In [40]:
d.min()

2

In [41]:
d.max()

29

In [42]:
d.mean()

12.222222222222221

In [43]:
np.median(d)

11.0

In [44]:
print(d)
print(d.T)

[[ 8  2  8]
 [14 29 12]
 [ 3 11 23]]
[[ 8 14  3]
 [ 2 29 11]
 [ 8 12 23]]


In [46]:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
print(a1)
print(a2)
a1.dot(a2)

[3 5 6 7]
[1 2 8 9]


124

In [48]:
d1=np.array([1,2,3,4])
np.array([d1,pow(d1,3)])

array([[ 1,  2,  3,  4],
       [ 1,  8, 27, 64]])

In [50]:
a=np.repeat([1,2,3,4],3)
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [51]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [58]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [64]:
x=np.array([1,2,3],[5,6,7])
x

TypeError: Field elements must be 2- or 3-tuples, got '5'